<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>53941f9e-c3a1-4627-9ae4-50176635196c</UserSecretsId>
		<DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
		<DockerfileContext>..\..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.6" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.6" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.6">
		</PackageReference>
		<PackageReference Include="Serilog" Version="4.3.1" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="9.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.6" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.7" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\Shared.csproj" />
	</ItemGroup>

</Project>
